[project]
name = "oshit"
version = "1.0.0"
description = "A terminal-based HackerNews reader"
authors = [
    { name = "Dave Pearson", email = "davep@davep.org" }
]
dependencies = [
    "httpx",
    "humanize>=4.8.0",
    "textual>=3.5.0",
    "xdg-base-dirs>=6.0.0",
]
readme = "README.md"
requires-python = ">=3.10"
license = { text = "GNU General Public License v3 or later (GPLv3+)" }
keywords = [
    "terminal",
    "tui",
    "chui",
    "news",
    "hackernews",
    "hacker-news",
    "orange-site",
    "reader",
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "Intended Audience :: End Users/Desktop",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Internet",
    "Topic :: Terminals",
    "Typing :: Typed",
]

[project.urls]
Homepage = "https://github.com/davep/oshit"
Repository = "https://github.com/davep/oshit"
Documentation = "https://github.com/davep/oshit"
Source = "https://github.com/davep/oshit"
Issues = "https://github.com/davep/oshit/issues"
Discussions = "https://github.com/davep/oshit/discussions"

[project.scripts]
oshit = "oshit.__main__:run"

[build-system]
requires = ["uv_build>=0.8.11,<0.9.0"]
build-backend = "uv_build"

[tool.uv]
managed = true
dev-dependencies = [
    "pre-commit>=4.2.0",
    "mypy>=1.16.1",
    "textual-dev>=1.7.0",
    "codespell>=2.4.1",
    "ruff>=0.12.9",
]

[[tool.uv.index]]
name = "testpypi"
url = "https://test.pypi.org/simple/"
publish-url = "https://test.pypi.org/legacy/"
explicit = true

[tool.pyright]
venvPath="."
venv=".venv"
exclude=[".venv"]
